# Generated by Django 3.0.5 on 2020-04-30 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DisciplineForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16, unique=True)),
            ],
            options={
                'verbose_name': 'Форма дисциплины',
                'verbose_name_plural': 'Формы дисциплины',
            },
        ),
        migrations.CreateModel(
            name='Fakultet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16, unique=True)),
            ],
            options={
                'verbose_name': 'Факультет',
                'verbose_name_plural': 'Факультеты',
            },
        ),
        migrations.CreateModel(
            name='Kafedra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16, unique=True)),
            ],
            options={
                'verbose_name': 'Кафедра',
                'verbose_name_plural': 'Кафедры',
            },
        ),
        migrations.CreateModel(
            name='Potok',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
            ],
            options={
                'verbose_name': 'Поток',
                'verbose_name_plural': 'Потоки',
            },
        ),
        migrations.CreateModel(
            name='Specialnost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16, unique=True)),
            ],
            options={
                'verbose_name': 'Специальность',
                'verbose_name_plural': 'Специальности',
            },
        ),
        migrations.CreateModel(
            name='Discipline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=5, verbose_name='Код')),
                ('shifr', models.CharField(default='НЕТ', max_length=10, verbose_name='Шифр')),
                ('name', models.CharField(max_length=128, verbose_name='Дисциплина')),
                ('kurs', models.IntegerField(verbose_name='Курс')),
                ('semestr', models.IntegerField(verbose_name='Семестр')),
                ('period', models.CharField(choices=[('осенний', 'осенний'), ('весенний', 'весенний')], default='осенний', max_length=16, verbose_name='Период')),
                ('nedeli', models.IntegerField(verbose_name='Недели')),
                ('trudoemkost', models.IntegerField(verbose_name='Трудоемкость')),
                ('chas_v_nedelu', models.IntegerField(verbose_name='Часы в неделю')),
                ('srs', models.IntegerField(verbose_name='Часов СРС')),
                ('chas_po_planu', models.IntegerField(verbose_name='Часов по плану')),
                ('student', models.IntegerField(verbose_name='Студенты')),
                ('group', models.IntegerField(verbose_name='Группы')),
                ('podgroup', models.IntegerField(verbose_name='Подгруппы')),
                ('lk', models.IntegerField(verbose_name='Лекции')),
                ('pr', models.IntegerField(verbose_name='Практические работы')),
                ('lr', models.IntegerField(verbose_name='Лабараторные работы')),
                ('k_tek', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Тек.кон.')),
                ('k_ekz', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Кон.экз')),
                ('zachet', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Зачет')),
                ('ekzamen', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Экзамен')),
                ('kontr_raboti', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Контр. раб.')),
                ('kr_kp', models.IntegerField(verbose_name='КР/КП')),
                ('vkr', models.IntegerField(verbose_name='ВКР')),
                ('pr_ped', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Практ.пед.')),
                ('pr_dr', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Практ.другая')),
                ('gak', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='ГАК')),
                ('aspirantura', models.IntegerField(verbose_name='Асп./Магистартура')),
                ('rukovodstvo', models.IntegerField(verbose_name='Руководство')),
                ('dop_chasi', models.IntegerField(verbose_name='Доп. часы')),
                ('fakultet', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Disciplines.Fakultet', verbose_name='Факультет')),
                ('form', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Disciplines.DisciplineForm', verbose_name='Форма')),
                ('kafedra', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Disciplines.Kafedra', verbose_name='Кафедра')),
                ('potok', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Disciplines.Potok', verbose_name='Поток')),
                ('specialnost', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Disciplines.Specialnost', verbose_name='Специальность')),
            ],
        ),
    ]
