# Generated by Django 3.0.5 on 2020-05-01 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Disciplines', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='discipline',
            options={'verbose_name': 'Дисциплина', 'verbose_name_plural': 'Дисциплины'},
        ),
    ]
