# Generated by Django 3.0.5 on 2020-05-01 18:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Prepods', '0004_remove_prepod_disciplines'),
        ('Disciplines', '0002_auto_20200501_1702'),
    ]

    operations = [
        migrations.AddField(
            model_name='discipline',
            name='prepod',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disciplines', to='Prepods.Prepod', verbose_name='Преподаватель'),
        ),
        migrations.AddField(
            model_name='discipline',
            name='prepod_access',
            field=models.ManyToManyField(related_name='discipl_access', to='Prepods.Prepod', verbose_name='Доступен для преподавателей'),
        ),
    ]
