# Generated by Django 3.0.5 on 2020-05-01 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Prepods', '0004_remove_prepod_disciplines'),
        ('Disciplines', '0004_remove_discipline_prepod_access'),
    ]

    operations = [
        migrations.AddField(
            model_name='discipline',
            name='prepod_available',
            field=models.ManyToManyField(related_name='discipl_access', to='Prepods.Prepod', verbose_name='Доступен для преподавателей'),
        ),
    ]
