# Generated by Django 3.0.5 on 2020-05-05 22:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Disciplines', '0006_remove_discipline_prepod_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discipline',
            name='aspirantura',
            field=models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Асп./Магистартура'),
        ),
        migrations.AlterField(
            model_name='discipline',
            name='code',
            field=models.CharField(max_length=16, verbose_name='Код'),
        ),
        migrations.AlterField(
            model_name='discipline',
            name='dop_chasi',
            field=models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Доп. часы'),
        ),
        migrations.AlterField(
            model_name='discipline',
            name='kr_kp',
            field=models.DecimalField(decimal_places=2, max_digits=4, verbose_name='КР/КП'),
        ),
        migrations.AlterField(
            model_name='discipline',
            name='name',
            field=models.CharField(max_length=1024, verbose_name='Дисциплина'),
        ),
        migrations.AlterField(
            model_name='discipline',
            name='rukovodstvo',
            field=models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Руководство'),
        ),
        migrations.AlterField(
            model_name='discipline',
            name='vkr',
            field=models.DecimalField(decimal_places=2, max_digits=4, verbose_name='ВКР'),
        ),
        migrations.AlterField(
            model_name='disciplineform',
            name='name',
            field=models.CharField(max_length=256, unique=True),
        ),
        migrations.AlterField(
            model_name='fakultet',
            name='name',
            field=models.CharField(max_length=256, unique=True),
        ),
        migrations.AlterField(
            model_name='kafedra',
            name='name',
            field=models.CharField(max_length=256, unique=True),
        ),
        migrations.AlterField(
            model_name='potok',
            name='name',
            field=models.CharField(max_length=256, unique=True),
        ),
        migrations.AlterField(
            model_name='specialnost',
            name='name',
            field=models.CharField(max_length=256, unique=True),
        ),
        migrations.CreateModel(
            name='Nagruzka',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lk', models.IntegerField(verbose_name='Лекции')),
                ('pr', models.IntegerField(verbose_name='Практические работы')),
                ('lr', models.IntegerField(verbose_name='Лабараторные работы')),
                ('k_tek', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Тек.кон.')),
                ('k_ekz', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Кон.экз')),
                ('zachet', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Зачет')),
                ('ekzamen', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Экзамен')),
                ('kontr_raboti', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Контр. раб.')),
                ('kr_kp', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='КР/КП')),
                ('vkr', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='ВКР')),
                ('pr_ped', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Практ.пед.')),
                ('pr_dr', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Практ.другая')),
                ('gak', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='ГАК')),
                ('aspirantura', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Асп./Магистартура')),
                ('rukovodstvo', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Руководство')),
                ('dop_chasi', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Доп. часы')),
                ('discipline', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Disciplines.Discipline', verbose_name='Дисциплина')),
            ],
        ),
    ]
