# Generated by Django 3.0.5 on 2020-05-05 22:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Prepods', '0007_auto_20200505_2235'),
        ('Disciplines', '0007_auto_20200505_2217'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discipline',
            name='prepod',
        ),
        migrations.AddField(
            model_name='nagruzka',
            name='prepod',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Prepods.Prepod', verbose_name='Преподаватель'),
        ),
    ]
