# Generated by Django 3.0.5 on 2020-05-07 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Disciplines', '0008_auto_20200505_2235'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nagruzka',
            options={'verbose_name': 'Нагрузка', 'verbose_name_plural': 'Нагрузки'},
        ),
        migrations.AlterField(
            model_name='nagruzka',
            name='aspirantura',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='Асп./Магистартура'),
        ),
        migrations.AlterField(
            model_name='nagruzka',
            name='dop_chasi',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='Доп. часы'),
        ),
        migrations.AlterField(
            model_name='nagruzka',
            name='ekzamen',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='Экзамен'),
        ),
        migrations.AlterField(
            model_name='nagruzka',
            name='gak',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='ГАК'),
        ),
        migrations.AlterField(
            model_name='nagruzka',
            name='k_ekz',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='Кон.экз'),
        ),
        migrations.AlterField(
            model_name='nagruzka',
            name='k_tek',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='Тек.кон.'),
        ),
        migrations.AlterField(
            model_name='nagruzka',
            name='kontr_raboti',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='Контр. раб.'),
        ),
        migrations.AlterField(
            model_name='nagruzka',
            name='kr_kp',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='КР/КП'),
        ),
        migrations.AlterField(
            model_name='nagruzka',
            name='lk',
            field=models.IntegerField(default=0, verbose_name='Лекции'),
        ),
        migrations.AlterField(
            model_name='nagruzka',
            name='lr',
            field=models.IntegerField(default=0, verbose_name='Лабараторные работы'),
        ),
        migrations.AlterField(
            model_name='nagruzka',
            name='pr',
            field=models.IntegerField(default=0, verbose_name='Практические работы'),
        ),
        migrations.AlterField(
            model_name='nagruzka',
            name='pr_dr',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='Практ.другая'),
        ),
        migrations.AlterField(
            model_name='nagruzka',
            name='pr_ped',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='Практ.пед.'),
        ),
        migrations.AlterField(
            model_name='nagruzka',
            name='rukovodstvo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='Руководство'),
        ),
        migrations.AlterField(
            model_name='nagruzka',
            name='vkr',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='ВКР'),
        ),
        migrations.AlterField(
            model_name='nagruzka',
            name='zachet',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='Зачет'),
        ),
    ]
