# Generated by Django 3.0.5 on 2020-05-08 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Disciplines', '0009_auto_20200507_2213'),
    ]

    operations = [
        migrations.AddField(
            model_name='nagruzka',
            name='student',
            field=models.IntegerField(default=0, verbose_name='Студентов'),
        ),
    ]
