# Generated by Django 3.0.5 on 2020-05-08 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Disciplines', '0010_nagruzka_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nagruzka',
            name='student',
            field=models.IntegerField(verbose_name='Студентов'),
        ),
        migrations.CreateModel(
            name='Archive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt', models.DateTimeField(auto_now_add=True)),
                ('discipline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Disciplines.Discipline')),
            ],
        ),
        migrations.AddField(
            model_name='nagruzka',
            name='archive',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Disciplines.Archive'),
        ),
    ]
