# Generated by Django 3.0.5 on 2020-05-13 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Disciplines', '0012_auto_20200509_1404'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='archive',
            options={'ordering': ['-dt'], 'verbose_name': 'Архив', 'verbose_name_plural': 'Архивы'},
        ),
    ]
