# Generated by Django 3.0.5 on 2020-05-17 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Disciplines', '0013_auto_20200513_1601'),
    ]

    operations = [
        migrations.AddField(
            model_name='nagruzka',
            name='n_stavka',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
        migrations.AddField(
            model_name='nagruzka',
            name='pochasovka',
            field=models.BooleanField(default=False),
        ),
    ]
