# Generated by Django 3.0.5 on 2020-05-20 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Disciplines', '0015_nagruzka_summary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nagruzka',
            name='aspirantura',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Асп./Магистартура'),
        ),
        migrations.AlterField(
            model_name='nagruzka',
            name='dop_chasi',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Доп. часы'),
        ),
        migrations.AlterField(
            model_name='nagruzka',
            name='ekzamen',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Экзамен'),
        ),
        migrations.AlterField(
            model_name='nagruzka',
            name='gak',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='ГАК'),
        ),
        migrations.AlterField(
            model_name='nagruzka',
            name='k_ekz',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Кон.экз'),
        ),
        migrations.AlterField(
            model_name='nagruzka',
            name='k_tek',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Тек.кон.'),
        ),
        migrations.AlterField(
            model_name='nagruzka',
            name='kontr_raboti',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Контр. раб.'),
        ),
        migrations.AlterField(
            model_name='nagruzka',
            name='kr_kp',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='КР/КП'),
        ),
        migrations.AlterField(
            model_name='nagruzka',
            name='n_stavka',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='nagruzka',
            name='pr_dr',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Практ.другая'),
        ),
        migrations.AlterField(
            model_name='nagruzka',
            name='pr_ped',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Практ.пед.'),
        ),
        migrations.AlterField(
            model_name='nagruzka',
            name='rukovodstvo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Руководство'),
        ),
        migrations.AlterField(
            model_name='nagruzka',
            name='summary',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='nagruzka',
            name='vkr',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='ВКР'),
        ),
        migrations.AlterField(
            model_name='nagruzka',
            name='zachet',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Зачет'),
        ),
    ]
