# Generated by Django 3.0.5 on 2020-05-20 19:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Prepods', '0014_prepod_fio'),
        ('Disciplines', '0017_discipline_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='discipline',
            name='errors',
            field=models.BooleanField(default=True, verbose_name='Ошибки'),
        ),
        migrations.AlterField(
            model_name='discipline',
            name='aspirantura',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Асп./Магистартура'),
        ),
        migrations.AlterField(
            model_name='discipline',
            name='dop_chasi',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Доп. часы'),
        ),
        migrations.AlterField(
            model_name='discipline',
            name='ekzamen',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Экзамен'),
        ),
        migrations.AlterField(
            model_name='discipline',
            name='gak',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='ГАК'),
        ),
        migrations.AlterField(
            model_name='discipline',
            name='k_ekz',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Кон.экз'),
        ),
        migrations.AlterField(
            model_name='discipline',
            name='k_tek',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Тек.кон.'),
        ),
        migrations.AlterField(
            model_name='discipline',
            name='kontr_raboti',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Контр. раб.'),
        ),
        migrations.AlterField(
            model_name='discipline',
            name='kr_kp',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='КР/КП'),
        ),
        migrations.AlterField(
            model_name='discipline',
            name='pr_dr',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Практ.другая'),
        ),
        migrations.AlterField(
            model_name='discipline',
            name='pr_ped',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Практ.пед.'),
        ),
        migrations.AlterField(
            model_name='discipline',
            name='rukovodstvo',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Руководство'),
        ),
        migrations.AlterField(
            model_name='discipline',
            name='vkr',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='ВКР'),
        ),
        migrations.AlterField(
            model_name='discipline',
            name='zachet',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Зачет'),
        ),
        migrations.AlterField(
            model_name='nagruzka',
            name='discipline',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nagruzki', to='Disciplines.Discipline', verbose_name='Дисциплина'),
        ),
        migrations.AlterField(
            model_name='nagruzka',
            name='prepod',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nagruzki', to='Prepods.Prepod', verbose_name='Преподаватель'),
        ),
    ]
