# Generated by Django 3.0.5 on 2020-05-24 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Prepods', '0014_prepod_fio'),
        ('Disciplines', '0018_auto_20200520_1948'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='discipline',
            options={'ordering': ['code', 'name'], 'verbose_name': 'Дисциплина', 'verbose_name_plural': 'Дисциплины'},
        ),
        migrations.AlterField(
            model_name='nagruzka',
            name='archive',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nagruzki', to='Disciplines.Archive'),
        ),
        migrations.AlterField(
            model_name='nagruzka',
            name='discipline',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nagruzki', to='Disciplines.Discipline', verbose_name='Дисциплина'),
        ),
        migrations.AlterField(
            model_name='nagruzka',
            name='prepod',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nagruzki', to='Prepods.Prepod', verbose_name='Преподаватель'),
        ),
    ]
