# Generated by Django 3.0.5 on 2020-05-24 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Disciplines', '0019_auto_20200524_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discipline',
            name='code',
            field=models.IntegerField(verbose_name='Код'),
        ),
    ]
