# Generated by Django 3.0.5 on 2020-05-24 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Disciplines', '0020_auto_20200524_1707'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='discipline',
            options={'ordering': ['code'], 'verbose_name': 'Дисциплина', 'verbose_name_plural': 'Дисциплины'},
        ),
    ]
