# Generated by Django 3.0.5 on 2020-06-09 23:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Disciplines', '0022_auto_20200527_1750'),
    ]

    operations = [
        migrations.AddField(
            model_name='kafedra',
            name='fakultet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Disciplines.Fakultet'),
        ),
    ]
