# Generated by Django 3.0.5 on 2020-05-01 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dolzhnost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
            options={
                'verbose_name': 'Должность',
                'verbose_name_plural': 'Должности',
            },
        ),
        migrations.CreateModel(
            name='Prepod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=64, verbose_name='Фамилия')),
                ('first_name', models.CharField(max_length=64, verbose_name='Имя')),
                ('surname', models.CharField(max_length=64, verbose_name='Отчество')),
                ('kv_uroven', models.IntegerField(verbose_name='Кв. уровень')),
                ('n_stavka', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Н.Ставка')),
                ('pochasovka', models.BinaryField(default=False, verbose_name='Почасовка')),
                ('chasov_stavki', models.IntegerField(verbose_name='Часов ставки')),
                ('dolzhnost', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Prepods.Dolzhnost', verbose_name='Должность')),
            ],
            options={
                'verbose_name': 'Преподаватель',
                'verbose_name_plural': 'Преподаватели',
            },
        ),
    ]
