# Generated by Django 3.0.5 on 2020-05-01 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Prepods', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prepod',
            name='pochasovka',
            field=models.BooleanField(default=False, verbose_name='Почасовка'),
        ),
    ]
