# Generated by Django 3.0.5 on 2020-05-01 17:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Disciplines', '0002_auto_20200501_1702'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Prepods', '0002_auto_20200501_1705'),
    ]

    operations = [
        migrations.AddField(
            model_name='prepod',
            name='disciplines',
            field=models.ManyToManyField(to='Disciplines.Discipline', verbose_name='Дисциплины'),
        ),
        migrations.AddField(
            model_name='prepod',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='dolzhnost',
            name='name',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
