# Generated by Django 3.0.5 on 2020-05-05 22:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Prepods', '0004_remove_prepod_disciplines'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prepod',
            name='dolzhnost',
        ),
        migrations.AlterField(
            model_name='prepod',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prepod', to=settings.AUTH_USER_MODEL),
        ),
    ]
