# Generated by Django 3.0.5 on 2020-05-05 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Prepods', '0005_auto_20200505_2217'),
    ]

    operations = [
        migrations.AddField(
            model_name='prepod',
            name='dolzhnost',
            field=models.CharField(choices=[('Зав. кафедрой', 'Зав. кафедрой'), ('Декан', 'Декан'), ('Профессор', 'Профессор'), ('Доцент', 'Доцент'), ('Ст. преподаватель', 'Ст. преподаватель'), ('Ассистент', 'Ассистент')], default='Зав. кафедрой', max_length=64),
        ),
    ]
