# Generated by Django 3.0.5 on 2020-05-05 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Prepods', '0006_prepod_dolzhnost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prepod',
            name='n_stavka',
        ),
        migrations.RemoveField(
            model_name='prepod',
            name='pochasovka',
        ),
    ]
