# Generated by Django 3.0.5 on 2020-05-07 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Prepods', '0007_auto_20200505_2235'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prepod',
            options={'ordering': ['last_name'], 'verbose_name': 'Преподаватель', 'verbose_name_plural': 'Преподаватели'},
        ),
    ]
