# Generated by Django 3.0.5 on 2020-05-09 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Prepods', '0008_auto_20200507_2213'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Dolzhnost',
        ),
    ]
