# Generated by Django 3.0.5 on 2020-05-09 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Disciplines', '0012_auto_20200509_1404'),
        ('Prepods', '0009_delete_dolzhnost'),
    ]

    operations = [
        migrations.AddField(
            model_name='prepod',
            name='kafedra',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Disciplines.Kafedra'),
        ),
    ]
