# Generated by Django 3.0.5 on 2020-05-13 16:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Disciplines', '0013_auto_20200513_1601'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Prepods', '0010_prepod_kafedra'),
    ]

    operations = [
        migrations.AddField(
            model_name='prepod',
            name='prosmotr',
            field=models.BooleanField(default=False, verbose_name='Просмотр распределения по кафедре'),
        ),
        migrations.AddField(
            model_name='prepod',
            name='raspred',
            field=models.BooleanField(default=False, verbose_name='Доступ к распределению'),
        ),
        migrations.AlterField(
            model_name='prepod',
            name='kafedra',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Disciplines.Kafedra'),
        ),
        migrations.AlterField(
            model_name='prepod',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prepod', to=settings.AUTH_USER_MODEL),
        ),
    ]
