# Generated by Django 3.0.5 on 2020-05-17 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Prepods', '0012_auto_20200513_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prepod',
            name='prava',
            field=models.CharField(blank=True, choices=[('raspred', 'Распределение и просмотр'), ('prosmotr', 'Только просмотр по кафедре'), (None, 'Просмотр своих дисциплин')], default=None, max_length=128, null=True, verbose_name='Права'),
        ),
    ]
