# Generated by Django 3.0.5 on 2020-05-17 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Prepods', '0013_auto_20200517_1554'),
    ]

    operations = [
        migrations.AddField(
            model_name='prepod',
            name='fio',
            field=models.CharField(blank=True, default='', max_length=256, verbose_name='ФИО'),
        ),
    ]
