# Generated by Django 3.0.5 on 2020-05-27 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Prepods', '0014_prepod_fio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prepod',
            name='prava',
            field=models.CharField(choices=[('raspred', 'Распределение и просмотр'), ('prosmotr', 'Только просмотр по кафедре'), ('None', 'Просмотр своих дисциплин')], default='None', max_length=128, verbose_name='Права'),
        ),
    ]
