# Generated by Django 3.0.5 on 2020-05-31 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Prepods', '0017_prepod_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='prepod',
            name='dogovor',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='prepod',
            name='pkgd',
            field=models.CharField(choices=[('pps', 'ППС')], default='pps', max_length=32),
        ),
        migrations.AddField(
            model_name='prepod',
            name='srok_izbr',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='prepod',
            name='uch_stepen',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='prepod',
            name='uch_zvanie',
            field=models.CharField(blank=True, choices=[('docent', 'доцент'), ('prof', 'профессор')], max_length=32, null=True),
        ),
    ]
