# Generated by Django 3.0.5 on 2020-06-09 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Prepods', '0018_auto_20200531_1750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prepod',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email'),
        ),
    ]
